// <auto-generated />
using System;
using System.Collections.Generic;
using IntegrationPlatform.API.Data;
using IntegrationPlatform.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IntegrationPlatform.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IntegrationPlatform.API.Models.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("LastHeartbeat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Dictionary<string, object>>("Metrics")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProcessorCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<List<string>>("SupportedAdapters")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("TotalMemory")
                        .HasColumnType("bigint");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LastHeartbeat");

                    b.HasIndex("NodeName")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("IntegrationPlatform.API.Models.StepExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Dictionary<string, object>>("ExecutionMetrics")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<object>("OutputPreview")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("ProcessedRecords")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowExecutionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowExecutionId");

                    b.ToTable("StepExecutions");
                });

            modelBuilder.Entity("IntegrationPlatform.API.Models.SystemLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, object>>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Timestamp", "Level");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("IntegrationPlatform.API.Models.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedNodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, object>>("GlobalVariables")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("IntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<List<WorkflowStep>>("Steps")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedNodeId");

                    b.HasIndex("IsActive");

                    b.HasIndex("Status");

                    b.ToTable("WorkflowDefinitions");
                });

            modelBuilder.Entity("IntegrationPlatform.API.Models.WorkflowExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<List<StepExecution>>("StepExecutions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<TimeSpan?>("TotalDuration")
                        .HasColumnType("interval");

                    b.Property<long>("TotalRecordsProcessed")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.HasIndex("WorkflowDefinitionId");

                    b.ToTable("WorkflowExecutions");
                });

            modelBuilder.Entity("IntegrationPlatform.API.Models.WorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdapterType")
                        .HasColumnType("integer");

                    b.Property<Dictionary<string, object>>("Configuration")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<List<Guid>>("DependsOn")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("EnableTesting")
                        .HasColumnType("boolean");

                    b.Property<Dictionary<string, string>>("InputMapping")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Dictionary<string, string>>("OutputMapping")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TestData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionId");

                    b.ToTable("WorkflowSteps");
                });

            modelBuilder.Entity("IntegrationPlatform.API.Models.StepExecution", b =>
                {
                    b.HasOne("IntegrationPlatform.API.Models.WorkflowExecution", "WorkflowExecution")
                        .WithMany()
                        .HasForeignKey("WorkflowExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowExecution");
                });

            modelBuilder.Entity("IntegrationPlatform.API.Models.WorkflowDefinition", b =>
                {
                    b.HasOne("IntegrationPlatform.API.Models.Node", "AssignedNode")
                        .WithMany("AssignedWorkflows")
                        .HasForeignKey("AssignedNodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedNode");
                });

            modelBuilder.Entity("IntegrationPlatform.API.Models.WorkflowExecution", b =>
                {
                    b.HasOne("IntegrationPlatform.API.Models.Node", "ExecutedBy")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IntegrationPlatform.API.Models.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("Executions")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutedBy");

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("IntegrationPlatform.API.Models.WorkflowStep", b =>
                {
                    b.HasOne("IntegrationPlatform.API.Models.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("IntegrationPlatform.API.Models.Node", b =>
                {
                    b.Navigation("AssignedWorkflows");
                });

            modelBuilder.Entity("IntegrationPlatform.API.Models.WorkflowDefinition", b =>
                {
                    b.Navigation("Executions");
                });
#pragma warning restore 612, 618
        }
    }
}
